# Use root/example as user/password credentials
version: '3.1'

services:

  chatbotapi:
    image: chatbotapi:latest
    restart: always
    ports:
      - "8000:8000"

  mongo:
    image: mongo:5.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: apassword # use a secret instead!